# Generated by Django 5.1.2 on 2024-10-17 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_category_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_title', models.CharField(max_length=1000)),
                ('d_content', models.TextField()),
                ('d_img_url', models.URLField(blank=True)),
                ('d_created_at', models.DateField(auto_now_add=True)),
                ('d_slug', models.SlugField(unique=True)),
                ('d_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.lcategory')),
            ],
        ),
    ]
